name: Nest.js CI/CD

on:
  push:
    branches:
      - feature/ec2

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install pnpm -g

      - name: Install dependencies
        run: pnpm install

      - name: Build Nest.js app
        run: pnpm build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/project/web3-university-backend/
            source ~/.bashrc
            export NODE_PATH=/home/ubuntu/.nvm/versions/node/v22.14.0/lib/node_modules
            export PATH="$PATH:/home/ubuntu/.nvm/versions/node/v22.14.0/bin"
            git pull origin feature/ec2
            /home/ubuntu/.nvm/versions/node/v22.14.0/bin/pnpm install
            /home/ubuntu/.nvm/versions/node/v22.14.0/bin/pnpm build
            /home/ubuntu/.nvm/versions/node/v22.14.0/bin/pm2 restart web3-university-api 